// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpYnbsJ1j08tyzrUgjguj08ltSICU08yE',
    appId: '1:598899500712:web:3731ada5c7bf59e16a049d',
    messagingSenderId: '598899500712',
    projectId: 'catatanku-5a341',
    authDomain: 'catatanku-5a341.firebaseapp.com',
    storageBucket: 'catatanku-5a341.firebasestorage.app',
    measurementId: 'G-4H8X777F42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSA-R6l0Brujx3WaR7YCQuBZXAUTKzGgI',
    appId: '1:598899500712:android:e1dba7bab6d564426a049d',
    messagingSenderId: '598899500712',
    projectId: 'catatanku-5a341',
    storageBucket: 'catatanku-5a341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMs6M_fYsiG9UkbWFc9bbHAKZHLUlOAaE',
    appId: '1:598899500712:ios:b2edf970948089786a049d',
    messagingSenderId: '598899500712',
    projectId: 'catatanku-5a341',
    storageBucket: 'catatanku-5a341.firebasestorage.app',
    iosBundleId: 'com.example.catatanku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMs6M_fYsiG9UkbWFc9bbHAKZHLUlOAaE',
    appId: '1:598899500712:ios:b2edf970948089786a049d',
    messagingSenderId: '598899500712',
    projectId: 'catatanku-5a341',
    storageBucket: 'catatanku-5a341.firebasestorage.app',
    iosBundleId: 'com.example.catatanku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpYnbsJ1j08tyzrUgjguj08ltSICU08yE',
    appId: '1:598899500712:web:d2fb8398c8e2ee676a049d',
    messagingSenderId: '598899500712',
    projectId: 'catatanku-5a341',
    authDomain: 'catatanku-5a341.firebaseapp.com',
    storageBucket: 'catatanku-5a341.firebasestorage.app',
    measurementId: 'G-LF6V6XWCX6',
  );
}
